language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install coveralls
  - pip install Django==$DJANGO
  - pip install -U pytest-cov
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests, e.g. python setup.py test
script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv cov

after_success:
  - coveralls

